export const ALPR_PROFILES = [
  {
    id: "sharp_read",
    label: "High detail",
    short: "DETAIL",
    resolution: "2304x1296",
    fps: 24,
    processFps: 12,
    purpose: "plate detail",
    bitrate: "10 Mbps",
  },
  {
    id: "fast_lane",
    label: "Fast traffic",
    short: "FAST",
    resolution: "1920x1080",
    fps: 60,
    processFps: 30,
    purpose: "fast traffic",
    bitrate: "12 Mbps",
  },
  {
    id: "track_boost",
    label: "Tracking priority",
    short: "TRACK",
    resolution: "1280x720",
    fps: 60,
    processFps: 45,
    purpose: "smooth tracking",
    bitrate: "8 Mbps",
  },
  {
    id: "night_boost",
    label: "Low light",
    short: "NIGHT",
    resolution: "1920x1080",
    fps: 20,
    processFps: 10,
    purpose: "low light / IR",
    bitrate: "9 Mbps",
  },
  {
    id: "workstation_track",
    label: "Workstation tracking",
    short: "WORKSTN",
    resolution: "1920x1080",
    fps: 60,
    processFps: 60,
    purpose: "max tracking cadence",
    bitrate: "14 Mbps",
  },
  {
    id: "gpu_detail",
    label: "GPU detail",
    short: "GPU",
    resolution: "2560x1440",
    fps: 30,
    processFps: 30,
    purpose: "high-resolution GPU",
    bitrate: "18 Mbps",
  },
  {
    id: "edge_economy",
    label: "Edge economy",
    short: "ECO",
    resolution: "1280x720",
    fps: 30,
    processFps: 8,
    purpose: "low power",
    bitrate: "5 Mbps",
  },
];

export function profileById(id) {
  const normalized = id === "pi_economy" ? "edge_economy" : id;
  return ALPR_PROFILES.find((p) => p.id === normalized) || ALPR_PROFILES[0];
}
